# Generated by Django 4.2.3 on 2023-07-13 09:57

import courses.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_video_text_image_file_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="content",
            options={"ordering": ["order"]},
        ),
        migrations.AddField(
            model_name="content",
            name="order",
            field=courses.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
